[package]
name = "TransportContract"
version = "1.0.0"
authors = []

[addresses]
TransportContractAddress = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]